title: "팔월삼일"
author: 리크루터의 일상★
email: official@aug3rd.co.kr
description: > # this means to ignore newlines until "show_exerpts:"
 완전 문과of문과 리크루터가 만들어본 우리회사 블로그.
show_excerpts: true # set to true to show excerpts on the homepage
url: "https://aug03rd.github.io"
baseurl: "/aug03rd"
remote_theme: thelehhman/texture
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
navigation: 
- title: Daily
url: "https://aug03rd.github.io/daily"
- title: From Team
url: "https://aug03rd.github.io/from-team"
style: blue
  title: 팔월삼일
  tagline: 리쿠르터의 일상
  date_format: "%b %-d, %Y"
  style: blue 
  showNav: true
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: null 
    github:  AUG03RD
    linkedIn: null
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture


plugins:
 - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin
  
